# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

	fitboxA = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-26 17:45:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
	methodA = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-26 19:00:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	fitboxB = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-27 07:00:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
	methodB = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-27 09:00:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	methodC = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-27 17:45:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	methodD = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-27 09:00:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	methodE = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-28 17:45:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	methodF = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-29 09:00:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	methodG = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-29 17:45:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	fitboxC = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-27 19:00:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")

	fitboxD = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-28 06:00:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
	fitboxE = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-28 12:30:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
	fitboxF = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-28 19:00:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
fitboxG = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-29 07:00:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
fitboxH = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-29 12:00:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
fitboxI = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-29 16:30:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")





yogaA = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-26 18:15:00", description: "Fusing traditional vinyasa methodology with contemporary dynamic flow, this uplifting yoga practice integrates breath and movement, inner and outer alignment, strength and flexibility accompanied by steady rhythmic tunes. Open classes appeal to students of all levels, while the advanced class allows experience students to enhance their practice with challenging poses. The basic classes appeal to new students or anyone who wants to refine their practice.")
yogaB = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-26 19:30:00", description: "Exhale Chill involves sequenced restorative and yin yoga postures designed to balance, calm and repair. Supported by props including bolsters and blankets, these long-hold poses allow your entire body to stretch gently, enhanced by meditation and deep breathing. Exhale Chill is the perfect complement to Core Fusion and more rigorous yoga classes.")
yogaC = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-27 07:00:00", description: "Get ready to sweat in this athletically and mentally challenging yoga class that is designed to fire you up from the inside out. Set to invigorating music, each class is a unique mix of dynamic movements and static holds crafted to build strength and endurance, tone your limbs, and tighten your core.")
yogaD = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-27 18:00:00", description: "Get ready to sweat in this athletically and mentally challenging yoga class that is designed to fire you up from the inside out. Set to invigorating music, each class is a unique mix of dynamic movements and static holds crafted to build strength and endurance, tone your limbs, and tighten your core.")
yogaE = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-28 12:15:00", description: "Fusing traditional vinyasa methodology with contemporary dynamic flow, this uplifting yoga practice integrates breath and movement, inner and outer alignment, strength and flexibility accompanied by steady rhythmic tunes. Open classes appeal to students of all levels, while the advanced class allows experience students to enhance their practice with challenging poses. The basic classes appeal to new students or anyone who wants to refine their practice.
")
yogaF = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-28 19:30:00", description: "Exhale Chill involves sequenced restorative and yin yoga postures designed to balance, calm and repair. Supported by props including bolsters and blankets, these long-hold poses allow your entire body to stretch gently, enhanced by meditation and deep breathing. Exhale Chill is the perfect complement to Core Fusion and more rigorous yoga classes.")
yogaG = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-29 12:15:00", description: "Get ready to sweat in this athletically and mentally challenging yoga class that is designed to fire you up from the inside out. Set to invigorating music, each class is a unique mix of dynamic movements and static holds crafted to build strength and endurance, tone your limbs, and tighten your core.")

yogaH = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Downtown", activity: "Yoga", time: "2016-07-28 18:30:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaI = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-07-28 20:00:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaJ = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-07-29 06:30:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaK = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-07-29 10:30:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaL = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-07-29 12:00:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaM = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-07-29 16:30:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaN = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-07-29 18:30:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaO = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-07-30 09:00:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaP = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-07-30 10:00:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaQ = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-07-30 12:00:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaR = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-07-30 16:30:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaS = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-07-31 10:00:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaT = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-07-31 10:30:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaU = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-08-01 06:30:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaV = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-08-01 10:30:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaW = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-08-01 12:00:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaX = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-08-01 18:30:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaY = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-08-02 12:00:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
yogaZ = Studio.create(name: "Love Life Wellness Center", address: "584 NW 27th St, Miami, FL 33127", phone: "(954) 294-1722", lat: 25.801484, lng: -80.2071077, area: "Wynwood", activity: "Yoga", time: "2016-08-02 18:30:00", description: "Love Life Wellness Center is a full circle hub for health-conscious individuals. Here you will experience services of well-being and meet like-minded individuals.")
















barreA = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-26 19:00:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreB = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-27 09:30:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreC = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-27 17:45:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreD = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-28 06:45:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreE = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-28 19:00:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreF = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-29 08:00:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreG = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-29 12:30:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreH = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Brickell", activity: "Barre", time: "2016-07-29 12:30:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")





pilatesA = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-26 15:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesB = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-26 17:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesC = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-26 18:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesD = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-27 07:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesE = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-27 09:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesF = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-27 12:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesG = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-27 15:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesH = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-27 20:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesI = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 07:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesJ = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 09:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesK = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 11:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesL = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 12:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesM = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 15:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesN = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 16:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesO = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 19:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesP = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-29 07:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesQ = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-29 09:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesR = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-29 11:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesS = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-29 14:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesT = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-29 17:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")

pilatesAA = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-27 06:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAB = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-27 08:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAC = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-27 17:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAD = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-28 06:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAE = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-28 07:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAF = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-28 08:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAG = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-28 09:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAH = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-28 12:00:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAI = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-28 16:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAJ = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-28 18:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAK = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-28 19:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAL = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-29 06:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAM = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-29 07:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAN = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-29 08:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAO = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-29 09:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAP = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-29 17:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAQ = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-28 17:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")
pilatesAR = Studio.create(name: "NuShape Studio", address: "121 SE 2nd Ave, Miami, FL 33131", phone: "(305) 967-7516", lat: 25.7729671, lng: -80.1922956, area: "Downtown", activity: "Pilates", time: "2016-07-27 07:30:00", description: "NuShape 50-minute class on the evolutionary Megaformer will make you sweat, shake and feel your muscles burn. Lagree Fitness™ is an exclusive workout designed to strengthen, tighten, and tone the body quickly and safely. The workout is intense on the muscles, but is low-impact and safe on the joints. This workout is largely based on the holistic principles of Pilates, but also emphasizes the strength training and cardio elements not inherent to Pilates to achieve muscle definition faster than traditional Pilates and/or weight training alone.")


pilatesBA = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-27 07:00:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBB = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-27 12:15:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBC = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-27 17:30:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBD = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-27 18:30:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBE = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-28 06:00:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBF = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-28 07:00:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBG = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-28 12:15:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBH = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-28 17:30:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBI = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-28 18:30:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBJ = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-28 19:30:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBK = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-29 07:00:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBL = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-29 09:30:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBM = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-29 12:15:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBN = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-29 18:00:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBO = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-30 09:30:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBP = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-30 10:30:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")
pilatesBQ = Studio.create(name: "RedBike", address: "1399 SW 1st Ave, Miami, FL 33130", phone: "(305) 646-1499", lat: 25.7609914, lng: -80.1969536, area: "Brickell", activity: "Cycling", time: "2016-07-30 11:30:00", description: "As the first dedicated cycle studio in Brickell, RedBike reinvents the ride, creating an exhilarating, rhythm-based full-body work out in only 45 min.")


pilatesBR = Studio.create(name: "Kenergy Pilates", address: "3404 NW 7th Ave, Miami, FL 33127", phone: "(305) 336-9601", lat: 25.8084264, lng: -80.2096769, area: "Wynwood", activity: "Pilates", time: "2016-07-27 08:30:00", description: "Kenergy is a Pilates studio founded by Karina Ramirez. This studio believes the pilates method is a post-rehabilitation tool and enhances athletic performance at all levels. MUST have Reformer experience or have taken a private class with Carina before booking a class.")
pilatesBS = Studio.create(name: "Kenergy Pilates", address: "3404 NW 7th Ave, Miami, FL 33127", phone: "(305) 336-9601", lat: 25.8084264, lng: -80.2096769, area: "Wynwood", activity: "Pilates", time: "2016-07-27 09:35:00", description: "Kenergy is a Pilates studio founded by Karina Ramirez. This studio believes the pilates method is a post-rehabilitation tool and enhances athletic performance at all levels. MUST have Reformer experience or have taken a private class with Carina before booking a class.")
pilatesBA = Studio.create(name: "Kenergy Pilates", address: "3404 NW 7th Ave, Miami, FL 33127", phone: "(305) 336-9601", lat: 25.8084264, lng: -80.2096769, area: "Wynwood", activity: "Pilates", time: "2016-07-27 18:00:00", description: "Kenergy is a Pilates studio founded by Karina Ramirez. This studio believes the pilates method is a post-rehabilitation tool and enhances athletic performance at all levels. MUST have Reformer experience or have taken a private class with Carina before booking a class.")
pilatesBT = Studio.create(name: "Kenergy Pilates", address: "3404 NW 7th Ave, Miami, FL 33127", phone: "(305) 336-9601", lat: 25.8084264, lng: -80.2096769, area: "Wynwood", activity: "Pilates", time: "2016-07-28 08:30:00", description: "Kenergy is a Pilates studio founded by Karina Ramirez. This studio believes the pilates method is a post-rehabilitation tool and enhances athletic performance at all levels. MUST have Reformer experience or have taken a private class with Carina before booking a class.")
pilatesBU = Studio.create(name: "Kenergy Pilates", address: "3404 NW 7th Ave, Miami, FL 33127", phone: "(305) 336-9601", lat: 25.8084264, lng: -80.2096769, area: "Wynwood", activity: "Pilates", time: "2016-07-28 09:35:00", description: "Kenergy is a Pilates studio founded by Karina Ramirez. This studio believes the pilates method is a post-rehabilitation tool and enhances athletic performance at all levels. MUST have Reformer experience or have taken a private class with Carina before booking a class.")
pilatesBV = Studio.create(name: "Kenergy Pilates", address: "3404 NW 7th Ave, Miami, FL 33127", phone: "(305) 336-9601", lat: 25.8084264, lng: -80.2096769, area: "Wynwood", activity: "Pilates", time: "2016-07-29 08:30:00", description: "Kenergy is a Pilates studio founded by Karina Ramirez. This studio believes the pilates method is a post-rehabilitation tool and enhances athletic performance at all levels. MUST have Reformer experience or have taken a private class with Carina before booking a class.")
pilatesBW = Studio.create(name: "Kenergy Pilates", address: "3404 NW 7th Ave, Miami, FL 33127", phone: "(305) 336-9601", lat: 25.8084264, lng: -80.2096769, area: "Wynwood", activity: "Pilates", time: "2016-07-29 09:35:00", description: "Kenergy is a Pilates studio founded by Karina Ramirez. This studio believes the pilates method is a post-rehabilitation tool and enhances athletic performance at all levels. MUST have Reformer experience or have taken a private class with Carina before booking a class.")
pilatesBX = Studio.create(name: "Kenergy Pilates", address: "3404 NW 7th Ave, Miami, FL 33127", phone: "(305) 336-9601", lat: 25.8084264, lng: -80.2096769, area: "Wynwood", activity: "Pilates", time: "2016-08-01 08:30:00", description: "Kenergy is a Pilates studio founded by Karina Ramirez. This studio believes the pilates method is a post-rehabilitation tool and enhances athletic performance at all levels. MUST have Reformer experience or have taken a private class with Carina before booking a class.")
pilatesBY = Studio.create(name: "Kenergy Pilates", address: "3404 NW 7th Ave, Miami, FL 33127", phone: "(305) 336-9601", lat: 25.8084264, lng: -80.2096769, area: "Wynwood", activity: "Pilates", time: "2016-08-01 18:00:00", description: "Kenergy is a Pilates studio founded by Karina Ramirez. This studio believes the pilates method is a post-rehabilitation tool and enhances athletic performance at all levels. MUST have Reformer experience or have taken a private class with Carina before booking a class.")
pilatesBZ = Studio.create(name: "Kenergy Pilates", address: "3404 NW 7th Ave, Miami, FL 33127", phone: "(305) 336-9601", lat: 25.8084264, lng: -80.2096769, area: "Wynwood", activity: "Pilates", time: "2016-08-02 08:30:00", description: "Kenergy is a Pilates studio founded by Karina Ramirez. This studio believes the pilates method is a post-rehabilitation tool and enhances athletic performance at all levels. MUST have Reformer experience or have taken a private class with Carina before booking a class.")
pilatesAS = Studio.create(name: "Kenergy Pilates", address: "3404 NW 7th Ave, Miami, FL 33127", phone: "(305) 336-9601", lat: 25.8084264, lng: -80.2096769, area: "Wynwood", activity: "Pilates", time: "2016-08-02 09:35:00", description: "Kenergy is a Pilates studio founded by Karina Ramirez. This studio believes the pilates method is a post-rehabilitation tool and enhances athletic performance at all levels. MUST have Reformer experience or have taken a private class with Carina before booking a class.")
pilatesAT = Studio.create(name: "Kenergy Pilates", address: "3404 NW 7th Ave, Miami, FL 33127", phone: "(305) 336-9601", lat: 25.8084264, lng: -80.2096769, area: "Wynwood", activity: "Pilates", time: "2016-08-03 16:00:00", description: "Kenergy is a Pilates studio founded by Karina Ramirez. This studio believes the pilates method is a post-rehabilitation tool and enhances athletic performance at all levels. MUST have Reformer experience or have taken a private class with Carina before booking a class.")


CycleA = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-07-28 18:30:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleB = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-07-28 19:00:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleC = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-07-29 09:00:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleD = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-07-29 18:00:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleE = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-07-30 09:00:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleF = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-07-30 09:30:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleG = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-07-30 10:30:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleH = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-07-31 10:00:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleI = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-07-31 11:00:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleJ = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-08-01 09:00:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleK = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-08-01 17:00:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleL = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-08-01 17:30:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleM = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-08-01 18:30:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleN = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-08-01 19:30:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleO = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-08-02 07:30:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleP = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-08-02 09:00:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleQ = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-08-02 18:30:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleR = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-08-02 19:30:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")
CycleR = Studio.create(name: "Wynwheels", address: "56 NE 29th St, Miami, FL 33137", phone: "(305) 209-2201", lat: 25.8036821, lng: -80.1959093, area: "Wynwood", activity: "Cycling", time: "2016-08-02 20:30:00", description: "Get in the best shape of your life and have fun doing it. Wynwheels brings to Midtown Miami the most innovative form of Indoor cycling.")

BoxA = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-28 07:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxB = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-28 09:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxC = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-28 10:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxD = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-28 12:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxE = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-28 17:45:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxF = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-28 18:45:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxG = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-28 19:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxH = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-28 20:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxI = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-29 07:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxJ = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-29 09:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxK = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-29 12:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxL = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-29 17:45:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxM = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-29 18:45:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxN = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-29 19:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxO = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-29 20:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxP = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-30 07:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxQ = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-30 09:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxR = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-30 10:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxS = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-30 12:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxT = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-30 17:45:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxU = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-30 18:30:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxV = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-30 19:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxW = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-30 20:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxX = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-31 07:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxY = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-31 09:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBA = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-31 12:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBB = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-31 17:45:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBC = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-31 18:45:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBD = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-31 19:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBE = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-07-31 20:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBF = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-08-01 07:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBG = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-08-01 09:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBH = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-08-01 10:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBI = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-08-01 12:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBJ = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-08-01 17:45:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBK = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-08-01 19:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBL = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-08-02 10:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBM = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-08-02 12:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")
BoxBN = Studio.create(name: "Fight Club", address: "120 NE 20TH STREET, MIAMI, FL 33137", phone: "(305) 573-7400", lat: 25.7954587, lng: -80.81946895, area: "Downtown", activity: "Boxing", time: "2016-08-03 12:00:00", description: "Fight Club promotes a holistic approach to health. Your body, mind and spirit must work together to create energy and vitality. The variety of different classes and workout options will help you find balance in all areas of your life.")





























