# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

	fitboxA = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-26 17:45:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
	methodA = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-26 19:00:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	fitboxB = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-27 07:00:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
	methodB = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-27 09:00:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	methodC = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-27 17:45:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	methodD = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-27 09:00:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	methodE = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-28 17:45:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	methodF = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-29 09:00:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	methodG = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-29 17:45:00", description: "Our Fitbox Method fundamentals class doesn’t come easy! Focusing on the heavy bag, you’ll learn boxing movement, punch combinations, and proper punching form while performing body weight exercises in between rounds. This class builds technique, endurance, and uses every muscle in your body.")
	fitboxC = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-27 19:00:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")

	fitboxD = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-28 06:00:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
	fitboxE = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-28 12:30:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
	fitboxF = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-28 19:00:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
fitboxG = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-29 07:00:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
fitboxH = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-29 12:00:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")
fitboxI = Studio.create(name: "FITBOX", address: "1756 North Bayshore Drive, Suite 119 Miami, FL 33132", phone: "(305) 978-3961", lat: 25.792934, lng: -80.188875, area: "Wynwood", activity: "Boxing", time: "2016-07-29 16:30:00", description: "Our most revolutionary workout ever created! This class is the epitome of our Fitbox methodology. Although it is a total body workout, each day focuses on two or three muscle groups to ensure muscle definition and toning in all the right places. This class uses all three training elements: cardio boxing, resistance/strength training, and Schwinn Airdyne Pro Fan Bikes. Every class is different and you will never plateau.
This class puts you in the right heart rate target zone and produces a “calorie afterburn effect” known as excess post-exercise oxygen consumption (EPOC). EPOC is a process of increased metabolism for 24 to 36 hours after the workout. You will burn an average of 1000 calories per class.")





yogaA = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-26 18:15:00", description: "Fusing traditional vinyasa methodology with contemporary dynamic flow, this uplifting yoga practice integrates breath and movement, inner and outer alignment, strength and flexibility accompanied by steady rhythmic tunes. Open classes appeal to students of all levels, while the advanced class allows experience students to enhance their practice with challenging poses. The basic classes appeal to new students or anyone who wants to refine their practice.")
yogaB = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-26 19:30:00", description: "Exhale Chill involves sequenced restorative and yin yoga postures designed to balance, calm and repair. Supported by props including bolsters and blankets, these long-hold poses allow your entire body to stretch gently, enhanced by meditation and deep breathing. Exhale Chill is the perfect complement to Core Fusion and more rigorous yoga classes.")
yogaC = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-27 07:00:00", description: "Get ready to sweat in this athletically and mentally challenging yoga class that is designed to fire you up from the inside out. Set to invigorating music, each class is a unique mix of dynamic movements and static holds crafted to build strength and endurance, tone your limbs, and tighten your core.")
yogaD = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-27 18:00:00", description: "Get ready to sweat in this athletically and mentally challenging yoga class that is designed to fire you up from the inside out. Set to invigorating music, each class is a unique mix of dynamic movements and static holds crafted to build strength and endurance, tone your limbs, and tighten your core.")
yogaE = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-28 12:15:00", description: "Fusing traditional vinyasa methodology with contemporary dynamic flow, this uplifting yoga practice integrates breath and movement, inner and outer alignment, strength and flexibility accompanied by steady rhythmic tunes. Open classes appeal to students of all levels, while the advanced class allows experience students to enhance their practice with challenging poses. The basic classes appeal to new students or anyone who wants to refine their practice.
")
yogaF = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-28 19:30:00", description: "Exhale Chill involves sequenced restorative and yin yoga postures designed to balance, calm and repair. Supported by props including bolsters and blankets, these long-hold poses allow your entire body to stretch gently, enhanced by meditation and deep breathing. Exhale Chill is the perfect complement to Core Fusion and more rigorous yoga classes.")
yogaG = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-29 12:15:00", description: "Get ready to sweat in this athletically and mentally challenging yoga class that is designed to fire you up from the inside out. Set to invigorating music, each class is a unique mix of dynamic movements and static holds crafted to build strength and endurance, tone your limbs, and tighten your core.")
yogaH = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Yoga", time: "2016-07-29 18:00:00", description: "Fusing traditional vinyasa methodology with contemporary dynamic flow, this uplifting yoga practice integrates breath and movement, inner and outer alignment, strength and flexibility accompanied by steady rhythmic tunes. Open classes appeal to students of all levels, while the advanced class allows experience students to enhance their practice with challenging poses. The basic classes appeal to new students or anyone who wants to refine their practice.")

barreA = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-26 19:00:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreB = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-27 09:30:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreC = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-27 17:45:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreD = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-28 06:45:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreE = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-28 19:00:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreF = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-29 08:00:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreG = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Downtown", activity: "Barre", time: "2016-07-29 12:30:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")
barreH = Studio.create(name: "EXHALE", address: "EPIC Hotel, 270 Biscayne Blvd Way, Miami, FL 33131", phone: "(305) 423-3900", lat: 25.7705359, lng: -80.1918046, area: "Brickell", activity: "Barre", time: "2016-07-29 12:30:00", description: "Hit the barre for our signature full body workout designed to give you chiseled abs, toned legs, cut arms, and a high, lifted butt. This ballet inspired, core-centric class focuses on isolated exercises, alignment, flexibility and posture as you work through targeted mindful muscle movements. Push yourself to the limit — and then find balance — as every hard worked muscled is followed by a deep, relaxing stretch. Suitable for all fitness levels, we invite you to choose from Basic, Open (to all), or Advanced classes. Socks required. Exhale’s no-slip grip socks required!")





pilatesA = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-26 15:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesB = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-26 17:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesC = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-26 18:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesD = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-27 07:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesE = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-27 09:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesF = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-27 12:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesG = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-27 15:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesH = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-27 20:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesI = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 07:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesJ = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 09:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesK = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 11:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesL = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 12:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesM = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 15:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesN = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 16:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesO = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-28 19:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesP = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-29 07:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesQ = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-29 09:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesR = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-29 11:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesS = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-29 14:00:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")
pilatesT = Studio.create(name: "House of Movement", address: "1900 Brickell Ave, Miami, FL 33129", phone: "(305) 200-5911", lat: 25.7546675, lng: -80.1982805, area: "Brickell", activity: "Pilates", time: "2016-07-29 17:30:00", description: "Exercise system performed on special equipment developed by Joseph Pilates to strengthen muscles, increase flexibility and improve overall health. Machines include Reformer, Cadillac and Exo chair. In each class you will work using a combination of the machines. Pilates focuses on engaging the mind with the body and is performed with attention to the breath, proper form and efficient movement patterns.")


